### ISSUE TITLE
[BUG] Won't start due to issue with libc.so.6 file missing !

### ISSUE THREAD

**Issue by vincegre** [joshuar/go-hass-agent#1]
**Describe the bug**
Complains about a libc.so.6 dependency missing but file exists on my system, and exit.

**To Reproduce**
1. Install the deb package on Debian 11
2. Start the go-hass-agent program
3.  Program exit immediately complaining about missing dependencies:
```
root@fixe:/lib/x86_64-linux-gnu# go-hass-agent 
go-hass-agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by go-hass-agent)
go-hass-agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by go-hass-agent)

```
but the file exists on my system (it's a link to the real file)

**Expected behavior**
Program starts normally

Can do some additional tests if needed ;)

Thanks

Vincèn

**Comment by joshuar** [comment]
Hey @vincegre thanks for trying out go-hass-agent!

This is a tough one. This looks to be because I created the deb/rpm/binaries on Fedora 37, which has a newer version of glibc than Debian 11. It's likely a dependency that go-hass-agent uses might need a newer glibc than you have on your distro, hence why you get this error.

If you are familiar with Go development, you could try grabbing the source of GitHub and trying to compile it yourself. However, it's possible the glibc problem is just one of many as it might be that the version of Go, and/or the other dependencies it relies on might cause problems that need fixing due to the differing versions.

I am not sure I have an easy way to build and develop in a way that would allow compatibility with distros like Debian 11. I'll have to see what is possible but no guarantees. 

In the meantime, I'll add a compatibility section to the README to reflect that unfortunately, go-hass-agent does not work on Debian Stable at the moment :frowning:

**Comment by vincegre** [comment]
Hi @joshuar 

Thanks for your answer and help ;) so I have installed go on my Debian 11 and downloaded the github repo to try to run it locally by hand.
When I run the go command it succeeds to retrieve nearly all dependencies out of a "gl" dependency but I have no idea if it's a go dependency I can install or a system dependency :( Any idea what it is ? I include the log of it below:

```
vincen@fixe:~/Bureau/go-hass-agent-main$ go run .
go: downloading github.com/rs/zerolog v1.29.0
go: downloading github.com/spf13/cobra v1.6.1
go: downloading fyne.io/fyne/v2 v2.3.1
go: downloading github.com/go-playground/validator/v10 v10.11.2
go: downloading github.com/grandcat/zeroconf v1.0.0
go: downloading github.com/jeandeaual/go-locale v0.0.0-20220711133428-7de61946b173
go: downloading golang.org/x/text v0.8.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/fsnotify/fsnotify v1.6.0
go: downloading github.com/godbus/dbus/v5 v5.1.0
go: downloading golang.org/x/sys v0.6.0
go: downloading github.com/yuin/goldmark v1.4.13
go: downloading github.com/carlmjohnson/requests v0.22.3
go: downloading github.com/cenkalti/backoff/v4 v4.2.0
go: downloading github.com/cenkalti/backoff v2.2.1+incompatible
go: downloading nhooyr.io/websocket v1.8.7
go: downloading git.lukeshu.com/go/libsystemd v0.5.3
go: downloading github.com/acobaugh/osrelease v0.1.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/iancoleman/strcase v0.2.0
go: downloading github.com/maltegrosse/go-geoclue2 v0.1.1
go: downloading github.com/miekg/dns v1.1.52
go: downloading golang.org/x/net v0.8.0
go: downloading github.com/go-playground/universal-translator v0.18.1
go: downloading github.com/leodido/go-urn v1.2.1
go: downloading golang.org/x/crypto v0.5.0
go: downloading fyne.io/systray v1.10.1-0.20230207085535-4a244dbb9d03
go: downloading github.com/fyne-io/image v0.0.0-20221020213044-f609c6a24345
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20221017161538-93cebf72946b
go: downloading github.com/fredbi/uri v0.1.0
go: downloading github.com/go-text/typesetting v0.0.0-20221212183139-1eb938670a1f
go: downloading github.com/goki/freetype v0.0.0-20220119013949-7a161fd3728c
go: downloading github.com/srwiley/rasterx v0.0.0-20210519020934-456a8d69b780
go: downloading golang.org/x/image v0.0.0-20220601225756-64ec528b34cd
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/klauspost/compress v1.10.3
go: downloading github.com/go-playground/locales v0.14.1
go: downloading github.com/go-gl/gl v0.0.0-20211210172815-726fda9656d6
go: downloading github.com/srwiley/oksvg v0.0.0-20220731023508-a61f04f16b76
go: downloading github.com/jsummers/gobmp v0.0.0-20151104160322-e2ba15ffa76e
go: downloading github.com/benoitkugler/textlayout v0.3.0
go build github.com/go-gl/gl/v3.2-core/gl:
# pkg-config --cflags  -- gl gl
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
pkg-config: exit status 1
# github.com/go-gl/glfw/v3.3/glfw
In file included from ./glfw/src/internal.h:188,
                 from ./glfw/src/context.c:30,
                 from ../../go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20221017161538-93cebf72946b/c_glfw.go:4:
./glfw/src/x11_platform.h:36:10: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
   36 | #include <X11/Xcursor/Xcursor.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
vincen@fixe:~/Bureau/go-hass-agent-main$ 


```

**Comment by joshuar** [comment]
Hey @vincegre,

It looks like a few more development packages are needed on your system. I think this is the complete list you would need:

- libx11-dev
- libxcursor-dev
- libxrandr-dev
- libxinerama-dev
- libxi-dev
- libglx-dev
- libgl-dev
- libxxf86vm-dev

I've managed to get a Debian VM up and running and I've made some changes to the code that seem to get it to be able to bring up the registration window at least...

Can you try grabbing the source from GitHub after installing all the packages above and try the `go run .` again?

**Comment by vincegre** [comment]
Hi @joshuar 

Thanks a lot for your help and I installed all dependencies you indicated, redownloaded project from github and now it's running, I have been able to start it, it has detected HA instance on my LAN and I have been able to put a long live token in it ;)
![Screenshot_20230414_090548](https://user-images.githubusercontent.com/3164888/231970111-c52ad48e-642d-4828-bff8-7de39dffcec1.png)
![Screenshot_20230414_090705](https://user-images.githubusercontent.com/3164888/231970127-b7f999e3-61c9-4173-bf63-6cf8179d78c6.png)
It still displays some warning/errors when starting:
```
vincen@fixe:~/Bureau/go-hass-agent-main$ go run .
go: downloading github.com/shirou/gopsutil/v3 v3.23.3
go: downloading github.com/tklauser/go-sysconf v0.3.11
go: downloading github.com/tklauser/numcpus v0.6.0
9:05AM INF Starting agent.
9:05AM WRN No suitable existing config found! Starting new registration process
9:05AM ERR Unable to retrieve property org.freedesktop.hostname1.HardwareVendor (org.freedesktop.hostname1) error="Unknown interface org.freedesktop.hostname1 or property HardwareVendor."                                                                                                 
9:05AM ERR Unable to retrieve property org.freedesktop.hostname1.HardwareModel (org.freedesktop.hostname1) error="Unknown interface org.freedesktop.hostname1 or property HardwareModel."                                                                                                   
9:05AM INF Looking for Home Assistant instances on the network...

```
but it doesn't prevent it to run ;)
Is there an easy way to transform that go program in a binary all packed one that I could automatically start with system ?

**Comment by joshuar** [comment]
I'm so glad you were able to get it working! Nice work! I'll have to look into how I can replicate this process in a more automated way so the deb files I produce work and you won't need to keep 

There would be a few more steps to package up what you've done as a deb. I use a tool called goreleaser and it has some other Go development dependancies that need to be installed and run for it to work.

What you can do instead is generate a binary with `go build` as is as there are no additional files required for it to run and use this binary as is. To integrate it a bit better into your desktop:

- Copy the binary to somewhere like `/usr/local/bin`.
- Edit the `go-hass-agent.desktop` file in the `assets/` directory to adjust the `Path` line to where you copied the binary.
- Copy the `.desktop` file to `/usr/local/share/applications`

You should then have an entry for go-hass-agent in your desktop environment and you could set it to auto-start with the session.

I've fixed those two errors about HardwareVendor and HardwareModel now. 

Yes, location might be inaccurate or vary a bit without dedicated GPS hardware. For me, it puts me at my internet providers office location :) I have dissassociated it's location with my user in Home Assistant (so it reverts to using my phone and watch).

**Comment by vincegre** [comment]
> What you can do instead is generate a binary with `go build` as is as there are no additional files required for it to run and use this binary as is. To integrate it a bit better into your desktop:

Thanks a lot for all the explanations and I'll give at a try but unhappy I don't know what modifications you made in code but I'm no more able to run it now after update from github on my desktop PC:

```
vincen@fixe:~/Bureau/go-hass-agent-main$ go run .
internal/agent/agent.go:25:12: pattern VERSION: no matching files found
vincen@fixe:~/Bureau/go-hass-agent-main$ 

```

**Comment by joshuar** [comment]
The `VERSION` file would be embedded in the binaries. You can recreate it by copying the version number:

```shell
echo "v0.0.4" > internal/agent/VERSION
```

Though I'm hoping the v0.0.5-alpha version I just released will fix the need for you to download and run the source directly. With v0.0.5-alpha, I've managed to build and package a binary that seems to work on my Debian 11 VM.  Can yo try downloading the `go-hass-agent.tar.xz` for the v0.0.5-alpha release:

https://github.com/joshuar/go-hass-agent/releases/download/v0.0.5-alpha/go-hass-agent.tar.xz

There will be a binary for the agent within the archive at `usr/local/bin/go-hass-agent`. Hopefully that runs for you without issues. 

If this binary works, you can then install the archive on your system under `/usr/local` with the following command:

```shell
tar -C / -xf go-hass-agent.tar.xz
```

That will put the binary under `/usr/local/bin` and install a desktop file that will allow the agent to appear in your app list of your desktop.

**Comment by vincegre** [comment]
you are fantastic @joshuar it works now without problem of dependencies on my Debian 11 and so I have been able to install in my startup program on my desktop :+1: 
So far only issue is localisation, it generates that error in console from time to time (probably related at fact that location reported is wrong !):

```
vincen@fixe:~/Bureau/go-hass-agent/usr/local/bin$ ./go-hass-agent 
8:46AM INF Starting agent.
8:46AM ERR Unable to send request with body:
        {"type":"update_location","data":{"gps":[46.51220143988481,6.6698],"gps_accuracy":8000,"speed":-1,"altitude":-9223372036854775808}}
         error="response error for https://hooks.nabu.casa/gAAAAABkOPt6GLWxhV-peXqep_V-UolVLp57tT5ngTZ3v4u-8MF4p7t1yUP69AHCzCE6c_g-eD9-0Q0Uvt8q5CCzncK_6FkdVmLq9E7feYarTlGr7YQZKO9Yivr9jPh28JgzK9TyPx8w2zJ9KWssSc9Lu9n7Mc6zN-CeNEme96gdzP2jQu2i1jU=: unexpected status: 502"
```

**Comment by joshuar** [comment]
Hey @vincegre that's great to hear! I'm so glad we got it working easier for you (and anyone else who runs Debian). 

That error looks like a temporary one. `unexpected status: 502`, the `502` would potentially indicate something on the server side. Good news is that it just means the location reported in Home Assistant won't be as up-to-date and hopefully the next location update will go through successfully.

**Comment by joshuar** [comment]
As I believe the issues are now fixed and I've been able to reliably produce a binary that works on Debian. I'll close this issue off. If there is still a problem, please re-open and I'll look to address it!

**Comment by vincegre** [comment]
Sorry @joshuar but problem is not fixed :( I just installed latest release on a laptop running debian 11 and that never got go-hass before and here is result when I try to run it (deb installation went well without any problem ;)

```
root@pingouin-portable:~# go-hass-agent 
go-hass-agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by go-hass-agent)
go-hass-agent: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by go-hass-agent)
root@pingouin-portable:~# 

```

**Comment by joshuar** [comment]
Hey @vincegre are you using the `.deb` or the `.tar.xz` for installation? The `.deb` will only work on Ubuntu, the `.tar.xz` is built in a way that should support Debian.  

If you used the deb, could you try uninstalling and then reinstalling with the `.tar.xz`? The `.tar.xz` contains a `Makefile` that can help with installation. The following commands should work:

```shell
mkdir /tmp/go-hass-agent
tar -C /tmp/go-hass-agent -xf go-hass-agent.tar.xz
cd /tmp/go-hass-agent
make install
```

I'll see what I can do to name the release assets to make it clearer which Linux distribution can use them and also update the README.

**Comment by vincegre** [comment]
> are you using the `.deb` or the `.tar.xz` for installation? The `.deb` will only work on Ubuntu, the `.tar.xz` is built in a way that should support Debian.

You should make it a lot more clear that deb is only for Ubuntu, deb being main format for debian that is the base of ubuntu ;)
I succeeded to build it with the .tar.xz ;) My only concern now is that it doesn't accept Nabu casa URL :( It works only in local ? It expects a port in url which is non sense with nabu casa url :(

**Comment by joshuar** [comment]
Hey @vincegre, can you try with the 1.3.1 release? It should fix the requirement to use a `hostname:port` and accept just a `hostname` when registering with a manually entered server.

**Comment by vincegre** [comment]
> Hey @vincegre, can you try with the 1.3.1 release? It should fix the requirement to use a `hostname:port` and accept just a `hostname` when registering with a manually entered server.

thanks but still exactly the same :( also what is the use of TLS option ? isn't it able to detect by itself if it's SSL or not depending of URL given ?

**Comment by joshuar** [comment]
With v1.3.1 and below, I had only supported a `hostname` or `hostname:port` format (without the `https://` or `http://` in the registration form. So it should work if you remove the `https://`. That's also why I had to have the *Use TLS* checkbox, because couldn't infer TLS from a hostname alone. In version 1.4.0 I just released, I've switched to only supported a URL or web address, so a full `https://hostname:port` (http or https and with or without the port). That simplifies the code somewhat as well making it easier for users such as yourself hopefully!

**Comment by vincegre** [comment]
> http or https and with or without the port). That simplifies the code somewhat as well making it easier for users such as yourself hopefully!

Thanks a lot for these updates and yep makes it easier to use but still some issues :(
If I put the nabu casa with a trailing / I get these errors:

`8:46AM FTL Could not register device with Home Assistant. error="response error for https://n6i71xxxxxxxxxxxxxx.ui.nabu.casa//api/mobile_app/registrations: unexpected status: 404"`

If I remove the trailing / I get these errors:

```
vincen@pingouin-portable:~$ go-hass-agent 
8:46AM INF Registration required. Starting registration process.
8:46AM INF Looking for Home Assistant instances on the network...


8:47AM ERR Unable to send request with body:
        {"type":"update_sensor_states","data":{"icon":"mdi:wifi-strength-3","state":75,"type":"sensor","unique_id":"wifi_signal_strength"}}
         error="Post \"https://hooks.nabu.casa/xxxxxxxxxxxxxxx-OoTTI797E9Ya3y0MSQ9tW1qRykA5kmUIOzBwsbU5MHXAtYkrh26DBjueJ9FR3Shvz8hJUXnh2beotFXZp7JOFrAOjjXX4BhqreYKmaqsW4O3dxB6xW30k782ShYArFuk0eaRK-Qvhou6HYV7PHr5g=\": context deadline exceeded"
8:48AM ERR Unable to send request with body:
        {"type":"get_config"}
         error="response error for https://hooks.nabu.casa/xxxxxxxxxx-OoTTI797E9Ya3y0MSQ9tW1qRykA5kmUIOzBwsbU5MHXAtYkrh26DBjueJ9FR3Shvz8hJUXnh2beotFXZp7JOFrAOjjXX4BhqreYKmaqsW4O3dxB6xW30k782ShYArFuk0eaRK-Qvhou6HYV7PHr5g=: unexpected status: 502"
8:49AM ERR Unable to send request with body:

```

**Comment by joshuar** [comment]
Hmm, could you try:

1. In Home Assistant navigate to the [Integrations Dashboard](https://my.home-assistant.io/redirect/integrations/). Remove the mobile app entry for the device in question. If you see more than 1 for your go-hass-agent device, remove them all.
2. Remove (or just move/backup) the go-hass-agent configuration directory `~/.config/fyne/com.github.joshuar.go-hass-agent/`
3. Run `go-hass-agent --debug` in a terminal. It will want to register without any configuration.
4. You'll get the usual registration window. Please enter your token and the url without a trailing slash. Submit the registration details.
5. It should successfully register and you should see the usual tray icon and sensors in Home Assistant again.

If that doesn't work, could you send through the log file `~/.config/fyne/com.github.joshuar.go-hass-agent/go-hass-agent.log`?

**Comment by joshuar** [comment]
Would you be able to try the steps in https://github.com/joshuar/go-hass-agent/issues/1#issuecomment-1617991413 with the version I've attached here. This has been built from a recent commit that has a number of fixes included.

[go-hass-agent.tar.gz](https://github.com/joshuar/go-hass-agent/files/11952823/go-hass-agent.tar.gz)

**Comment by vincegre** [comment]
> Would you be able to try the steps in [#1 (comment)](https://github.com/joshuar/go-hass-agent/issues/1#issuecomment-1617991413) with the version I've attached here. This has been built from a recent commit that has a number of fixes included.

Thanks a lot, works all good with that version :+1:

**Comment by joshuar** [comment]
Phew! That's good to hear, I'm glad it is now working! Thank you for your patience and assistance with debugging these issues!

**Comment by vincegre** [comment]
> Phew! That's good to hear, I'm glad it is now working! Thank you for your patience and assistance with debugging these issues!

Thanks for your patience too and help ;) One last thing it's not able to start automatically on Debian KDE. I have added it in autostartup program but it's not working ! I have to manually start it after login and also icon tray never shows up on KDE !
